### ISSUE TITLE
Elgépelt válasz

### ISSUE THREAD

**Issue by boapps** [nytud/HAPP#1]
A [happ_test.json 210. sorában](https://github.com/nytud/HAPP/blob/main/happ_test.json#L210) a `correct` mező értéke "a rabokat" kéne legyen.

**Comment by vadno** [comment]
Köszönöm, javítottam!

**Comment by boapps** [comment]
Köszönöm a nagyon gyors reakciót!

Közben találtam még ugyanilyen hibákat (ezek a `correct` értékek, amikhez nem tartozik szó szerint A vagy B válasz):
`happ_train.json`: `['Pókemger', 'a videojátékok', 'a motoros', 'a fagyasztü', 'Krisznej', 'Balázs', 'a rendőrség', 'az MIT']`

`happ_test.json`: `['a toll', 'A fa ', 'Picard kapitány', 'A szezámos csirkére. ', 'Az Egyesült Államok', 'Optimus', 'A TRON-rajongók', 'A tudósok']`

Kód, amivel ezek kijöttek:
```python
from datasets import load_dataset

dataset = load_dataset('json', data_files={'train': 'https://raw.githubusercontent.com/nytud/HAPP/main/happ_train.json', 'test': 'https://raw.githubusercontent.com/nytud/HAPP/main/happ_test.json'})

print(dataset.filter(lambda row: row['correct'] not in [row['answerA'], row['answerB']])['train']['correct'])
print(dataset.filter(lambda row: row['correct'] not in [row['answerA'], row['answerB']])['test']['correct'])
```

**Comment by vadno** [comment]
Köszönöm, ezeket is javítottam!
